<?php

use Illuminate\Database\Seeder;
use App\Audio;
use App\Book;

class AudioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $audios_data = [
            [
                'title' => 'شمارۀ 1',
                'file' => 'audio/mina3/1.mp3',
                'group_name' => 'درس 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 2',
                'file' => 'audio/mina3/2.mp3',
                'group_name' => 'درس 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 3',
                'file' => 'audio/mina3/3.mp3',
                'group_name' => 'درس 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 4',
                'file' => 'audio/mina3/4.mp3',
                'group_name' => 'درس 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 5',
                'file' => 'audio/mina3/5.mp3',
                'group_name' => 'درس 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 6',
                'file' => 'audio/mina3/6.mp3',
                'group_name' => 'درس 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 7',
                'file' => 'audio/mina3/7.mp3',
                'group_name' => 'درس 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 8',
                'file' => 'audio/mina3/8.mp3',
                'group_name' => 'درس 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 9',
                'file' => 'audio/mina3/9.mp3',
                'group_name' => 'درس 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 10',
                'file' => 'audio/mina3/10.mp3',
                'group_name' => 'درس 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 11',
                'file' => 'audio/mina3/11.mp3',
                'group_name' => 'درس 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 12',
                'file' => 'audio/mina3/12.mp3',
                'group_name' => 'درس 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 13',
                'file' => 'audio/mina3/13.mp3',
                'group_name' => 'درس 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 14',
                'file' => 'audio/mina3/14.mp3',
                'group_name' => 'درس 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 15',
                'file' => 'audio/mina3/15.mp3',
                'group_name' => 'درس 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 16',
                'file' => 'audio/mina3/16.mp3',
                'group_name' => 'درس 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 17',
                'file' => 'audio/mina3/17.mp3',
                'group_name' => 'درس 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 18',
                'file' => 'audio/mina3/18.mp3',
                'group_name' => 'درس 5',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 19',
                'file' => 'audio/mina3/19.mp3',
                'group_name' => 'درس 5',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 20',
                'file' => 'audio/mina3/20.mp3',
                'group_name' => 'درس 5',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 21',
                'file' => 'audio/mina3/21.mp3',
                'group_name' => 'درس 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 22',
                'file' => 'audio/mina3/22.mp3',
                'group_name' => 'درس 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 23',
                'file' => 'audio/mina3/23.mp3',
                'group_name' => 'درس 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 24',
                'file' => 'audio/mina3/24.mp3',
                'group_name' => 'درس 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 25',
                'file' => 'audio/mina3/25.mp3',
                'group_name' => 'درس 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 26',
                'file' => 'audio/mina3/26.mp3',
                'group_name' => 'درس 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 27',
                'file' => 'audio/mina3/27.mp3',
                'group_name' => 'درس 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 28',
                'file' => 'audio/mina3/28.mp3',
                'group_name' => 'درس 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 29',
                'file' => 'audio/mina3/29.mp3',
                'group_name' => 'درس 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 30',
                'file' => 'audio/mina3/30.mp3',
                'group_name' => 'درس 8',
                'group_order' => 8,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 31',
                'file' => 'audio/mina3/31.mp3',
                'group_name' => 'درس 8',
                'group_order' => 8,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 32',
                'file' => 'audio/mina3/32.mp3',
                'group_name' => 'درس 8',
                'group_order' => 8,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'شمارۀ 33',
                'file' => 'audio/mina3/33.mp3',
                'group_name' => 'درس 8',
                'group_order' => 8,
                'book_id' => Book::firstWhere('title_abbr', 'mina3')->id,
            ],
            [
                'title' => 'درس 1 وسیله های شخصی',
                'file' => 'audio/enjoyreading1/1.mp3',
                'group_name' => 'درس 1 وسیله های شخصی',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 2 خانوادۀ من',
                'file' => 'audio/enjoyreading1/2.mp3',
                'group_name' => 'درس 2 خانوادۀ من',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 3 کشور',
                'file' => 'audio/enjoyreading1/3.mp3',
                'group_name' => 'درس 3 کشور',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 4 مشاهیر',
                'file' => 'audio/enjoyreading1/4.mp3',
                'group_name' => 'درس 4 مشاهیر',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 5 دستور غذا',
                'file' => 'audio/enjoyreading1/5.mp3',
                'group_name' => 'درس 5 دستور غذا',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 6 آخر هفته',
                'file' => 'audio/enjoyreading1/6.mp3',
                'group_name' => 'درس 6 آخر هفته',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 7 خانه',
                'file' => 'audio/enjoyreading1/7.mp3',
                'group_name' => 'درس 7 خانه',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 8 کارهای روزانه',
                'file' => 'audio/enjoyreading1/8.mp3',
                'group_name' => 'درس 8 کارهای روزانه',
                'group_order' => 8,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 9 وعده ها و عدت های غذایی',
                'file' => 'audio/enjoyreading1/9.mp3',
                'group_name' => 'درس 9 وعده ها و عدت های غذایی',
                'group_order' => 9,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 10 رژیم غذایی سالم',
                'file' => 'audio/enjoyreading1/10.mp3',
                'group_name' => 'درس 10 رژیم غذایی سالم',
                'group_order' => 10,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 11 کتاب',
                'file' => 'audio/enjoyreading1/11.mp3',
                'group_name' => 'درس 11 کتاب',
                'group_order' => 11,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 12 وسایل نقلیه',
                'file' => 'audio/enjoyreading1/12.mp3',
                'group_name' => 'درس 12 وسایل نقلیه',
                'group_order' => 12,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 13 طبیعت',
                'file' => 'audio/enjoyreading1/13.mp3',
                'group_name' => 'درس 13 طبیعت',
                'group_order' => 13,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 14 ورزش',
                'file' => 'audio/enjoyreading1/14.mp3',
                'group_name' => 'درس 14 ورزش',
                'group_order' => 14,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 15 سفرنامه',
                'file' => 'audio/enjoyreading1/15.mp3',
                'group_name' => 'درس 15 سفرنامه',
                'group_order' => 15,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس 16 ارتباط',
                'file' => 'audio/enjoyreading1/16.mp3',
                'group_name' => 'درس 16 ارتباط',
                'group_order' => 16,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading1')->id,
            ],
            [
                'title' => 'درس اول: ایران در یونسکو',
                'file' => 'audio/enjoyreading4/1-1.mp3',
                'group_name' => 'بخش 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس دوم: جنگلهای هیرکانی',
                'file' => 'audio/enjoyreading4/1-2.mp3',
                'group_name' => 'بخش 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس اول: المپیک',
                'file' => 'audio/enjoyreading4/2-1.mp3',
                'group_name' => 'بخش 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس دوم: ورزش همگانی و قهرمانی',
                'file' => 'audio/enjoyreading4/2-2.mp3',
                'group_name' => 'بخش 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس اول: نان بازو',
                'file' => 'audio/enjoyreading4/3-1.mp3',
                'group_name' => 'بخش 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس دوم: کسب و کارهای نوپا',
                'file' => 'audio/enjoyreading4/3-2.mp3',
                'group_name' => 'بخش 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس اول: طب سنتی و نوین',
                'file' => 'audio/enjoyreading4/4-1.mp3',
                'group_name' => 'بخش 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس دوم: اهدای زندگی',
                'file' => 'audio/enjoyreading4/4-2.mp3',
                'group_name' => 'بخش 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس اول: یکی بخر، دو تا ببر',
                'file' => 'audio/enjoyreading4/5-1.mp3',
                'group_name' => 'بخش 5',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس دوم: نبوغ دردسرساز',
                'file' => 'audio/enjoyreading4/5-2.mp3',
                'group_name' => 'بخش 5',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس اول: خط و زبان',
                'file' => 'audio/enjoyreading4/6-1.mp3',
                'group_name' => 'بخش 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس دوم: از هیرمند تا ارس',
                'file' => 'audio/enjoyreading4/6-2.mp3',
                'group_name' => 'بخش 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس اول: گردشگری مذهبی',
                'file' => 'audio/enjoyreading4/7-1.mp3',
                'group_name' => 'بخش 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس دوم: کاروانسرا',
                'file' => 'audio/enjoyreading4/7-2.mp3',
                'group_name' => 'بخش 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس اول: کهکشان',
                'file' => 'audio/enjoyreading4/8-1.mp3',
                'group_name' => 'بخش 8',
                'group_order' => 8,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس دوم: نردبان آسمان',
                'file' => 'audio/enjoyreading4/8-2.mp3',
                'group_name' => 'بخش 8',
                'group_order' => 8,
                'book_id' => Book::firstWhere('title_abbr', 'enjoyreading4')->id,
            ],
            [
                'title' => 'درس 1 موقعیت جغرافیایی',
                'file' => 'audio/iranology1/fasl1-dars1.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 2 اقلیم و آب‌و‌هوا',
                'file' => 'audio/iranology1/fasl1-dars2.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 3 طبیعت',
                'file' => 'audio/iranology1/fasl1-dars3.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 4 پوشش گیاهی و جانوری',
                'file' => 'audio/iranology1/fasl1-dars4.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 1 تقسیمات کشوری',
                'file' => 'audio/iranology1/fasl2-dars1.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 2 زبان، دین و اقوام',
                'file' => 'audio/iranology1/fasl2-dars2.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 3 صنایع دستی',
                'file' => 'audio/iranology1/fasl2-dars3.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 4 صنایع ماشینی',
                'file' => 'audio/iranology1/fasl2-dars4.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 1 تقویم و گاه‌شماری',
                'file' => 'audio/iranology1/fasl3-dars1.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 2 آداب و رسوم مذهبی',
                'file' => 'audio/iranology1/fasl3-dars2.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 3 آداب و رسوم ملی',
                'file' => 'audio/iranology1/fasl3-dars3.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 1 ایران باستان (مادها و هخامنشیان)',
                'file' => 'audio/iranology1/fasl4-dars1.mp3',
                'group_name' => 'فصل 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 2 ایران باستان (از سلوکیان تا ساسانیان)',
                'file' => 'audio/iranology1/fasl4-dars2.mp3',
                'group_name' => 'فصل 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 3 دورۀ اسلامی (از ابتدا تا غزنویان)',
                'file' => 'audio/iranology1/fasl4-dars3.mp3',
                'group_name' => 'فصل 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 4 دورۀ اسلامی (از سلجوقیان تا تیموریان)',
                'file' => 'audio/iranology1/fasl4-dars4.mp3',
                'group_name' => 'فصل 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 5 دورۀ اسلامی (از صفویان تا قاجاریان)',
                'file' => 'audio/iranology1/fasl4-dars5.mp3',
                'group_name' => 'فصل 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 6 دورۀ اسلامی (از قاجاریان تا انقلاب اسلامی)',
                'file' => 'audio/iranology1/fasl4-dars6.mp3',
                'group_name' => 'فصل 4',
                'group_order' => 4,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 1 انقلاب اسلامی',
                'file' => 'audio/iranology1/fasl5-dars1.mp3',
                'group_name' => 'فصل 5',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 2 دفاع مقدس',
                'file' => 'audio/iranology1/fasl5-dars2.mp3',
                'group_name' => 'فصل 5',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 3 دستاوردهای انقلاب اسلامی',
                'file' => 'audio/iranology1/fasl5-dars3.mp3',
                'group_name' => 'فصل 5',
                'group_order' => 5,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 1 ادبیات ایران باستان',
                'file' => 'audio/iranology1/fasl6-dars1.mp3',
                'group_name' => 'فصل 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 2 ادبیات دورۀ اسلامی',
                'file' => 'audio/iranology1/fasl6-dars2.mp3',
                'group_name' => 'فصل 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 3 ادبیات معاصر',
                'file' => 'audio/iranology1/fasl6-dars3.mp3',
                'group_name' => 'فصل 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 4 مشاهیر ادبی',
                'file' => 'audio/iranology1/fasl6-dars4.mp3',
                'group_name' => 'فصل 6',
                'group_order' => 6,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 1 ریاضی و ستاره شناسی',
                'file' => 'audio/iranology1/fasl7-dars1.mp3',
                'group_name' => 'فصل 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 2 پزشکی',
                'file' => 'audio/iranology1/fasl7-dars2.mp3',
                'group_name' => 'فصل 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 3 معماری',
                'file' => 'audio/iranology1/fasl7-dars3.mp3',
                'group_name' => 'فصل 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 4 نقاشی',
                'file' => 'audio/iranology1/fasl7-dars4.mp3',
                'group_name' => 'فصل 7',
                'group_order' => 7,
                'book_id' => Book::firstWhere('title_abbr', 'iranology1')->id,
            ],
            [
                'title' => 'درس 1 آئین‌های ازدواج',
                'file' => 'audio/iranology2/fasl1-dars1.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 2 آئین‌های تولد',
                'file' => 'audio/iranology2/fasl1-dars2.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 3 شب‌نشینی',
                'file' => 'audio/iranology2/fasl1-dars3.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 4 غذاها',
                'file' => 'audio/iranology2/fasl1-dars4.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 5 طب',
                'file' => 'audio/iranology2/fasl1-dars5.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 6 ورزش باستانی',
                'file' => 'audio/iranology2/fasl1-dars6.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 7 پوشاک اقوام',
                'file' => 'audio/iranology2/fasl1-dars7.mp3',
                'group_name' => 'فصل 1',
                'group_order' => 1,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 1 موسیقی سنتی',
                'file' => 'audio/iranology2/fasl2-dars1.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 2 خوش‌نویسی',
                'file' => 'audio/iranology2/fasl2-dars2.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 3 نقاشی',
                'file' => 'audio/iranology2/fasl2-dars3.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 4 سینما',
                'file' => 'audio/iranology2/fasl2-dars4.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 5 نمایش',
                'file' => 'audio/iranology2/fasl2-dars5.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 6 انیمیشن',
                'file' => 'audio/iranology2/fasl2-dars6.mp3',
                'group_name' => 'فصل 2',
                'group_order' => 2,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 1 خانۀ ایرانی',
                'file' => 'audio/iranology2/fasl3-dars1.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 2 باغ ایرانی',
                'file' => 'audio/iranology2/fasl3-dars2.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 3 مساجد ایرانی',
                'file' => 'audio/iranology2/fasl3-dars3.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 4 کلیساها',
                'file' => 'audio/iranology2/fasl3-dars4.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 5 کاروان‌سراها',
                'file' => 'audio/iranology2/fasl3-dars5.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 6 بازارهای سنتی',
                'file' => 'audio/iranology2/fasl3-dars6.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
            [
                'title' => 'درس 7 شهرهای باستانی',
                'file' => 'audio/iranology2/fasl3-dars7.mp3',
                'group_name' => 'فصل 3',
                'group_order' => 3,
                'book_id' => Book::firstWhere('title_abbr', 'iranology2')->id,
            ],
        ];
        foreach ($audios_data as $audio_data) {
            $audio = new Audio;
            $audio->title = $audio_data['title'];
            $audio->file = $audio_data['file'];
            $audio->group_name = $audio_data['group_name'];
            $audio->group_order = $audio_data['group_order'];
            $audio->book_id = $audio_data['book_id'];
            $audio->save();
        }
    }
}
